### ISSUE TITLE
How to stop IBM from artificially inflating your conversation counts?

### ISSUE THREAD

**Issue by Confidenceiskey** [watson-developer-cloud/assistant-simple#194]
Just reading the documents from [this page](https://console.bluemix.net/docs/services/conversation/logs_oview.html#graphs-and-statistics) and quoting the below...

> Important: A 'conversation' is considered to be any set of messages sent or received by an application/bot, so if the service starts by saying "Hi, how can I help you?", and then the user closes their browser without responding, that message is included in the total conversation count.

Would someone be able to give me a hint where it would be best to stop this initial welcome message in the source code? Then I can just build the initial welcome message into the front-end and not be 'using' the IBM service when users are simply browsing my website.

My aim is to get the conversation count to start only once the user writes a message into the chat window. As the current setup is totally unfair and only seeks to inflate the conversation counts with website traffic (example: when users aren't using the chatbot service).

**Comment by mitchmason** [comment]
I want to make it clear that we do not use intro messages to inflate the conversation counts. There are many reasons for the intro message and first actions to come from the Watson service. Many clients like to randomly choose various intro messages which we can easily support through response variations. Also, most clients like to add user context and respond with a more personal introduction, which is better over the course of the conversation to reuse these variables. Third, many users are setting additional context and running other actions before the user types anything which is also can be easier to do through the dialog. Lastly, setting the intro message in the html file would require some development skills, and we would like users to be able to easily spin this up without too much coding if possible, so only teaching them dialog is much easier than teaching them html editing. 

That being said, I understand this will incur a single extra API call for you, so if this is undesired, you will have to remove the conversation_start dialog node from your dialog, and write some intro message into the html file of the app. Next, you'll need to edit conversation.js in the public file to remove the initial message at line 30. Just remove the api.sendmessage() all together so it doesn't run when the app loads. This way the first message sent comes from the user, and starts looking for a matching dialog node rather than giving the intro message.

**Comment by mitchmason** [comment]
For the most very basic intro message of all time, just add your text between the <div> on line 25, anything more fancy you'll have to figure it out yourself as I'm not that great at html and I basically just guess and check until I like it.

**Comment by Confidenceiskey** [comment]
Hey @mitchmason,

Thank you very much for the response and the guidance! That will be very helpful to get me going. It is a bit of a pain to jump into something when you don't fully understand the inner workings of everything, but knowing where I should focus my energy (specific files or sections) will help save me a ton of time! So thanks once again 👍 

And just to add...
Maybe I had used the wrong word choice in the title. I was just annoyed when I saw my conversation count (almost entirely from refreshing) when building out my website.

Don't get me wrong, this template is great! It saves a lot of time/hassle in trying to code it from scratch and getting everything to work properly. 

It is just that in my case, I find the count based on traffic (and not use) to be undesirable. If one has a website where only 20% of visitors end up using the chatbot service, then it becomes a big deal! Especially if one becomes a chatbot service provider and starts paying for the service.

**Comment by mitchmason** [comment]
You're welcome, thanks for clarifying :)
Most of our clients also hide the chat behind some kind of click like a 'click here to chat' button or something, to also avoid opening the chat at every page load. 
but this method will work as well if you want the chat window always ready to go

**Comment by Confidenceiskey** [comment]
No problem @mitchmason!

I just implemented exactly what you said, and it works beautifully! Thanks once again! Would have taken me a long time to figure out what to comment out in the JS code.

Yeah...I was also thinking about having an onclick (button) event to start the chat dialogue. However, I didn't quite like that as it would've made the user perform an extra click. But, now thinking about it....that could have also been done to a chat button (on the webpage) instead of from within the chat dialogue window. So that would have resulted in the same number of clicks. Anyways, I prefer this method.

Also, if anyone in the future is also wanting to change this, then as per Mitchmason's instructions....
##

### **Within the ```conversation.js``` file:**

comment out, or delete, the following code:
```Api.sendRequest('', null);```
##

### **In the ```index.html``` file:**

between this line of code
`<div id="scrollingChat"></div>`

add the following to keep the chat formatting consistent.

```
<div class="segments load">
  <div class="from-watson latest top">
    <div class="message-inner">
      <p>Your Greeting message here!</p>
    </div>
  </div>
</div>
```
