### ISSUE TITLE
Dialog-Response-Options: No Links

### ISSUE THREAD

**Issue by tkretsch** [watson-developer-cloud/assistant-simple#197]
Hi, I have created in the Dialog an Answer with Options. the Links you can click on in original Watson page "Try me" do not appear in the assistant-simple app. it only shows the "list label" can you fix this? Thanks & Greets.

**Comment by Oliver-I** [comment]
@tkretsch I'm not sure what the issue is here, the assistant-simple app and the "Try me" responses show the same list items (List Label), as this is the text to be seen when presented to an end-user. When the user clicks on an option the system will display the value (if it's different).

Please see the below example where I modified the value to "my lights" but the list label is set to "the lights".

If you are experiencing a different issue, please let me know.




![image](https://user-images.githubusercontent.com/24578377/45276020-4b709980-b503-11e8-8c2c-e4ead43e12eb.png)

**Comment by tkretsch** [comment]
Hi Oliver, 
I have copied  3 screenshots together:
1. the dialog (german)
2. the Try me dialog including the hyperlinks to klick
3. the simple app connected to the workspace (no hyperlinks to click)

if you click in 2. the hyperlink "Rechnungserklärung" the watson put the value "Erkläre mir meine Rechnung" into the chat. But in 3. if you can not click you will never see the value.

I would like to have the hyperlinks also in the simple app to click.

![watson_example](https://user-images.githubusercontent.com/25501379/45296841-a3a79b80-b503-11e8-993e-ace1e4030586.jpg)

**Comment by tkretsch** [comment]
When do you think you can fix it?

**Comment by Oliver-I** [comment]
@tkretsch This is working as expected in the sample app, lists can be clickable or not, as required by your solution - you would need to add the clickable code in your version of the sample app. However, if you want to use the UI code as is, please add "preference": "button", to the response code - which would be inserted just above the response_type:

        "preference": "button",
        "response_type": "option"
      }

**Comment by tkretsch** [comment]
perfekt, thanks a lot. I changed it and it works. for other people looking for it, here is the link to the documentation: [https://console.bluemix.net/docs/services/conversation/dialog-responses-json.html#defining-responses-using-the-json-editor](https://console.bluemix.net/docs/services/conversation/dialog-responses-json.html#defining-responses-using-the-json-editor)
