### ISSUE TITLE
I'm having trouble connecting to the server, please refresh the page

### ISSUE THREAD

**Issue by dandresv** [watson-developer-cloud/assistant-simple#224]
I have problems with my credentials since, I follow all the steps that indicate but it always answers me the following when I execute the command line npm start

"I'm having trouble connecting to the server, please refresh the page"

Attached url with some images of my credentials [https://drive.google.com/drive/folders/1mwT8pzuU7EGQkOn8TJiR1yUmZ06I_gwB?usp=sharing](url)

**Comment by obgvts** [comment]
I'm having the same issue. Seems to come from /api/session, https error code 404 - Not found. No idea what is not found. 

I'm pretty sure nothing wrong with my apikey, aim_url, assistant_id. Tested them on rest tester.

**Comment by Oliver-I** [comment]
@stevenpkg Can you take a look at this?

**Comment by stevenpkg** [comment]
@dandresv looking at your .env file I can see you have both username, password and IAM key. Please specify one or the other. Use a # to comment out variables you do not need:

#ASSISTANT_USERNAME=6a563286-afc2-49b8-9214-xxxxxxxxxx
#ASSISTANT_PASSWORD=d8T7Hxxxxxxx
#ASSISTANT_URL=https://gateway.watsonplatform.net/assistant/api

# OR IAM API key and URL

ASSISTANT_IAM_APIKEY=0adu5bk5RDQQqnWtxRufmST0dJlAnZv-xxxxxxxxxxxx
ASSISTANT_IAM_URL=https://gateway.watsonplatform.net/assistant/api

**Comment by dandresv** [comment]
@stevenpkg Make the corresponding changes and leave these variables ASSISTANT_ID, ASSISTANT_IAM_APIKEY, ASSISTANT_IAM_URL and I still get the same error, I'm reviewing from the browser console and I answered the following "Failed to load resource: the server responded with a status of 500 (Internal Server Error) ": 3000 / api / message

**Comment by stevenpkg** [comment]
@dandresv the problem I believe is getting the session key due to credentials not being correct. What error is printed on the backend.

put some debug code around this function, also you can turn on node debug

```
NODE_DEBUG=request npm start
```
```
function inputKeyDown(event, inputBox) {
    // Submit on enter key, dis-allowing blank messages
    if (event.keyCode === 13 && inputBox.value) {
      sendMessage(inputBox.value);
      // Clear input box for further messages
      inputBox.value = '';
      Common.fireEvent(inputBox, 'input');
    }
  }
```

**Comment by dandresv** [comment]
This is the error that is showing me in the app.js.

**(api/session)**
Error: Not Found
    at Request._callback (\assistant-simple\node_modules\watson-developer-cloud\lib\requestwrapper.js:102:21)
    at Request.self.callback (\assistant-simple\node_modules\watson-developer-cloud\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (\assistant-simple\node_modules\watson-developer-cloud\node_modules\request\request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Gunzip.<anonymous> (\assistant-simple\node_modules\watson-developer-cloud\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
  code: 404,
  error: 'Not Found',
  'x-global-transaction-id': 'ffea405d5c5c49b130e9497d'


**assistant.message**
Error: Missing required parameters: session_id
    at Object.getMissingParams (\assistant-simple\node_modules\watson-developer-cloud\lib\helper.js:95:11)
    at AssistantV2.message (\assistant-simple\node_modules\watson-developer-cloud\assistant\v2.js:178:38)
    at \assistant-simple\app.js:89:13
    at Layer.handle [as handle_request] (\assistant-simple\node_modules\express\lib\router\layer.js:95:5)
    at next (\assistant-simple\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (\assistant-simple\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (\assistant-simple\node_modules\express\lib\router\layer.js:95:5)
    at \assistant-simple\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (\assistant-simple\node_modules\express\lib\router\index.js:335:12)
    at next (\assistant-simple\node_modules\express\lib\router\index.js:275:10)

**Comment by stevenpkg** [comment]
@germanattanasio have you any thoughts why the session Id is failing?

**Comment by ElinShek** [comment]
I'm having the same issue here. It works with the username and password of the old Assistant, but it does not work with the new Assistant service credentials ASSISTANT_IAM_APIKEY, ASSISTANT_URL=https://gateway.watsonplatform.net/assistant/api/, and ASSISTANT_ID that I provide.

**Comment by stevenpkg** [comment]
Not sure ATM, will try and test some more with different account myself to see if I can replicate this issue. @ElinShek there is no need to put the iam_apikey and url in the V2 constructor, just have them in your .env file, make sure you only specify one type of login, username or aim

**Comment by ElinShek** [comment]
My simple app is working now. You have to make sure that you don't have the old service credentials in your environment still (i.e. ASSISTANT_USERNAME, ASSISTANT_PASSWORD, etc.) I used a new terminal and everything works with the IAM api key. FYI...

**Comment by ToniHuovinen** [comment]
> My simple app is working now. You have to make sure that you don't have the old service credentials in your environment still (i.e. ASSISTANT_USERNAME, ASSISTANT_PASSWORD, etc.) I used a new terminal and everything works with the IAM api key. FYI...

Could you open this little bit. I am having same issues and I can't seem to be able to solve it. Also I am bit confused on where I could find the needed information, I feel I have taken the wrong ones

**Comment by ElinShek** [comment]
ASSISTANT_IAM_APIKEY is used starting with Assistant version 2. If your Assistant is created during version 1 then you have to use the username and password. If you go to your dashboard in Bluemix, click on your Assistant instance, on the Manage page where there is a Launch tool button... there should be an API Key and a URL. API Key = ASSISTANT_IAM_APIKEY and URL = ASSISTANT_URL.

You also have to make sure you have an Assistant in place with a skill. Assuming you have a skill (aka workspace back then) all created. Go to Assistants tab and Create new, name the assistant with whatever you want and click on Create. Click on the newly created Assistant and add the skill to the assistant.
![image](https://user-images.githubusercontent.com/17606219/52726973-40bea280-2f82-11e9-9c6e-42b732656a12.png)
Then, go to View API Details. In here you will find your Assistant ID which is your ASSISTANT_ID in the .env file.

This combination worked for me...ASSISTANT_IAM_APIKEY, ASSISTANT_URL, and ASSISTANT_ID in the .env file and sourced in the environment where I do `npm start`. Comment out all the other variables in .env. Make sure you comment out before sourcing the .env file. Otherwise it will not work as it tries to use the other ones. So to be absolutely sure, in your terminal `echo $ASSISTANT_USERNAME` and the other variable that are commented out in your .env and make sure it doesn't exist.

Hope this helps.

**Comment by ToniHuovinen** [comment]
Thank you very much! I got it working. I had ASSISTANT_URL incorrect.

**Comment by huesoamz** [comment]
That it's the time of the "session"? how can configure that and the message?

Because a lot of times the demo show this: 

![image](https://user-images.githubusercontent.com/3308717/60627639-089aed80-9dc5-11e9-93fc-ce32e84fcf38.png)

NotFound: session id e6066d98-a3d1-489d-b91d-e44cdb616539 for agent instance 1ed2ee6d-9f40-4c62-bd2a-089081cef547

Full response:

https://jsonblob.com/41766720-9dde-11e9-af06-038bec3250b4

**Comment by Oliver-I** [comment]
@huesoamz That's correct, the error message will appear when the app can't connect to the assistant (when it times out after approx 5 mins, or you lose connection to the assistant).

**Comment by huesoamz** [comment]
> @huesoamz That's correct, the error message will appear when the app can't connect to the assistant (when it times out after approx 5 mins, or you lose connection to the assistant). By refreshing the page the app creates a new session ID and can interact with the assistant.

And how can increase that time?, 5 minutes its not enough and how customize the message for that error? (portuguese...spanish) I had more than 5 bots for migrate to this version (assistantv2 from conversation) and need to change that because are bots on produtions enviroments.
Could you please help me?
Thanks in advance,

**Comment by Oliver-I** [comment]
@huesoamz The timeout limit can be found in the assistant settings. Go to your Assistant and click on the Settings option (found on the right-hand side of the screen).

![image](https://user-images.githubusercontent.com/24578377/60670673-96a1d180-9eb4-11e9-9e8c-8259bb2ecf23.png)

Then select the Inactivity Timeout option from the left-hand menu. IT will show you the timeout limit applied to your assistant. Please note different plans have different maximum limits - for more information go to https://cloud.ibm.com/docs/services/assistant?topic=assistant-assistant-settings#assistant-settings.

![image](https://user-images.githubusercontent.com/24578377/60670698-a7524780-9eb4-11e9-8441-c1b4642a6a58.png)

**Comment by huesoamz** [comment]
Oliver very thanks for your support but the URL that you provide doenst work, I general we use "standard" plan, but the maximum in that cases its only 5 minutes...so for no create another 3 more assistants with 3 more highers plans only for see what its the maximum in each plan, could you plase tellme if exist a page that explain that? (the page gives 404)

And the other question is...why if my Assistant its on spanish I receive a message on english? how can customize this message "I'm having trouble connecting to the server, please refresh the page "
